version: "3.8"
services:
  backend:
    environment:
      NODE_ENV: development
    volumes:
      - ./backend:/app/medusa
      - backend_node_modules:/app/medusa/node_modules

  storefront:
    volumes:
      - ./storefront:/app/storefront
      - storefront_node_modules:/app/storefront/node_modules

volumes:
  storefront_node_modules:
  backend_node_modules:
