version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:test
    container_name: medusa-server
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/medusa-docker
      REDIS_URL: redis://cache
      NODE_ENV: development
      PORT: 9000
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/app/medusa
      - backend_node_modules:/app/medusa/node_modules

  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-docker

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    image: admin:test
    depends_on:
      - backend
    container_name: medusa-admin
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
    ports:
      - "7000:7000"

  storefront:
    build:
      context: ./storefront
      dockerfile: Dockerfile
    image: storefront:test
    container_name: medusa-storefront
    depends_on:
      - backend
    volumes:
      - ./storefront:/app/storefront
      - storefront_node_modules:/app/storefront/node_modules
    ports:
      - "8000:8000"

volumes:
  storefront_node_modules:
  backend_node_modules:
